[package]
name = "rust_organizer"
version = "0.1.0"
authors = ["TDH55 <taylorhoward1@wustl.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.21"